#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc rule -a Telegramdesktop desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^2'

bspc config pointer_modifier super

pgrep -x sxhkd > /dev/null || sxhkd -f & #запуск sxhkd
wal -R & #запуск pywal с предыдущей цветовой схемой
nitrogen --restore &
numlockx &
~/.config/polybar/forest/launch.sh & #скрипт запуска polybar,скопировать с https://github.com/polybar/polybar/wiki/
xsetroot -cursor_name left_ptr & #цивилизованный курсор
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle & #раскладка клавиатуры, модель чаще всего 105 но может быть и 104

# picom
killall picom; picom --config ~/.config/picom/picom.conf &
